--1) создание базы данных

CREATE DATABASE [StadiumServices]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StadiumServices', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StadiumServices.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StadiumServices_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StadiumServices_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [StadiumServices] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [StadiumServices] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [StadiumServices] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [StadiumServices] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [StadiumServices] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [StadiumServices] SET ARITHABORT OFF 
GO
ALTER DATABASE [StadiumServices] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [StadiumServices] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [StadiumServices] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [StadiumServices] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [StadiumServices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [StadiumServices] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [StadiumServices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [StadiumServices] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [StadiumServices] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [StadiumServices] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [StadiumServices] SET  DISABLE_BROKER 
GO
ALTER DATABASE [StadiumServices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [StadiumServices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [StadiumServices] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [StadiumServices] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [StadiumServices] SET  READ_WRITE 
GO
ALTER DATABASE [StadiumServices] SET RECOVERY FULL 
GO
ALTER DATABASE [StadiumServices] SET  MULTI_USER 
GO
ALTER DATABASE [StadiumServices] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [StadiumServices] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [StadiumServices] SET DELAYED_DURABILITY = DISABLED 
GO
USE [StadiumServices]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [StadiumServices]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [StadiumServices] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


--2) Создание схемы

USE [StadiumServices]
GO
CREATE SCHEMA [Food] AUTHORIZATION [db_owner]
GO

--3) Создание таблицы Customers

CREATE TABLE [Food].[Customers] 
(
 [CustomerID] [int] NOT NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
	[CustomerName] [nvarchar](150) NOT NULL,
	[RegistrationDate] [datetime] NOT NULL,
	[Comms] [nvarchar](500),
CONSTRAINT [PK_Food_Customers] PRIMARY KEY CLUSTERED 
(
  [CustomerID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)

--4) Создание таблицы Items
CREATE TABLE [Food].[Items](
	[ItemID] [int] NOT NULL,
	[ItemName] [nvarchar](200) NOT NULL,
	[Price] [decimal] (18,2) NOT NULL,
	[Balance] [int]  NOT NULL,
	[Comms] [nvarchar](500) NULL,
 CONSTRAINT [PK_Food_Items] PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

